import { Pacifico } from "next/font/google";
import "./globals.css";

const pacifico = Pacifico({
  subsets: ["latin", "vietnamese"],
  weight: "400",
});

export const metadata = {
  title: "Spell App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${pacifico.className} antialiased`}>{children}</body>
    </html>
  );
}
